### ISSUE TITLE
Implement wrapper function for AWS Lambda helpers

### ISSUE THREAD

**Issue by automatthew** [pandastrike/panda-sky#69]
It can, among other things, parse such headers as Authorization and Accept

Usage:

```coffee
  "#{fullName}-blurb-put": sky (request, context) ->
    console.log 'update', {request}

    try
      blurb = request.content
      key = request.url.path.key

      # editKey = request.headers.Authorization.split("BlurbAuth key=").pop()
      assert.equal request.authorization.scheme, "BlurbAuth"
      editKey = request.authorization.credentials.key
```

**Comment by automatthew** [comment]
Alternative:

```coffee
blurb-put: sky (request, context, derived) ->
  assert.equal derived.authorization.scheme, "BlurbAuth"

```

**Comment by maximbert** [comment]
Is this built-in already? or do I need to update Sky and re-deploy?

**Comment by automatthew** [comment]
No this is a design proposal.

**Comment by maximbert** [comment]
I like it.

**Comment by automatthew** [comment]
Now I'm thinking, in line with Dan's discussion of terminology:

```coffee
"#{fullName}-blurb-put": sky.method (request, context) ->

```

**Comment by dyoder** [comment]
I like `sky.method`. Partly because it gives us a namespace for additional helpers. I also prefer `context` with derived elements within it, because de-structuring. That said, I like `derived` to distinguish things parsed from the request. Probably too much, though, since, strictly speaking, `url.path.key` is derived. So maybe just leave it as `authorization`.

**Comment by automatthew** [comment]
Test showing usage:

https://github.com/pandastrike/panda-sky/blob/69-lambda-method/test/unit/sky_helpers.coffee
